// Generated by CoffeeScript 1.3.3
(function() {

  test("a basic test example", function() {
    var value;
    value = "hello";
    return equal(value, "hello", "We expect value to be hello");
  });

}).call(this);
