// Generated by CoffeeScript 1.3.3
(function() {
  var $FIXTURE, DATA, FIXTURE;

  FIXTURE = document.getElementById('qunit-fixture');

  DATA = [];

  $FIXTURE = $(FIXTURE);

  module("D3Chart");

  test("SVG element created", function() {
    var testChart;
    testChart = new D3Chart(FIXTURE, DATA);
    return ok($FIXTURE.find('svg').length, "Fixture element should contain a SVG element.");
  });

  test("Variable has basic properties", function() {
    var testChart;
    testChart = new D3Chart(FIXTURE, DATA);
    ok(testChart.svg, ".svg");
    return ok(testChart.plot, ".plot");
  });

  test("Default options loaded when none provided", function() {
    var testChart;
    testChart = new D3Chart(FIXTURE, DATA);
    return ok(testChart.option('margin'));
  });

  test("Provided options override defaults", function() {
    var options, testChart;
    options = {
      margin: {
        top: 0,
        left: 0
      }
    };
    testChart = new D3Chart(FIXTURE, DATA, options);
    equal(testChart.option('margin').top, options.margin.top);
    return equal(testChart.option('margin').bottom, 30, "Assuming the default is 30,    it's a private variable so we can't automatically pull it out to compare.");
  });

  test("postRender is called", function() {
    var block, options;
    options = {
      postRender: function() {
        throw "poop";
      }
    };
    block = function() {
      return new D3Chart(FIXTURE, DATA, options);
    };
    return throws(block, "poop");
  });

}).call(this);
